name:
channels:
  a:
    - embed:
        content: test
        title: e
        description: e
        author: e
        icon_url: e
    - msg: ":"
    - pin:
        name: hi
        range: [1,2,3]
